from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import h5py
import imageio.v2 as imageio
import numpy as np
import pyvista as pv

from src.utils.alpha_texture_processing import (
    AlphaTextureConfig,
    make_texture_image,
)


def load_pseudo3d_h5(input_h5: Path, geometry_key: str = "prior") -> dict[str, Any]:
    """
    Load pseudo-3D h5 generated by infer_video_to_pseudo3d_h5.py.

    Required keys:
      local_encoder_images
      frame_indices

    geometry_key=prior:
      frame_corners_world
      frame_mesh_vertices
      frame_mesh_faces
      pred_tracking

    geometry_key=corr:
      frame_corners_world_corr
      frame_mesh_vertices_corr
      frame_mesh_faces_corr
      pred_tracking_corr
    """
    input_h5 = Path(input_h5)

    if not input_h5.exists():
        raise FileNotFoundError(f"Input h5 not found: {input_h5}")

    if geometry_key == "prior":
        geometry_dataset_keys = {
            "frame_corners_world": "frame_corners_world",
            "frame_mesh_vertices": "frame_mesh_vertices",
            "frame_mesh_faces": "frame_mesh_faces",
            "pred_tracking": "pred_tracking",
        }
    elif geometry_key == "corr":
        geometry_dataset_keys = {
            "frame_corners_world": "frame_corners_world_corr",
            "frame_mesh_vertices": "frame_mesh_vertices_corr",
            "frame_mesh_faces": "frame_mesh_faces_corr",
            "pred_tracking": "pred_tracking_corr",
        }
    else:
        raise ValueError(f"Unknown geometry_key: {geometry_key}")

    with h5py.File(input_h5, "r") as f:
        required_keys = list(geometry_dataset_keys.values()) + [
            "local_encoder_images",
            "frame_indices",
        ]

        for key in required_keys:
            if key not in f:
                raise KeyError(
                    f"Required key '{key}' for geometry_key='{geometry_key}' "
                    f"not found in {input_h5}"
                )

        data = {
            "local_encoder_images": f["local_encoder_images"][:].astype(np.float32),
            "frame_corners_world": f[
                geometry_dataset_keys["frame_corners_world"]
            ][:].astype(np.float32),
            "frame_mesh_vertices": f[
                geometry_dataset_keys["frame_mesh_vertices"]
            ][:].astype(np.float32),
            "frame_mesh_faces": f[
                geometry_dataset_keys["frame_mesh_faces"]
            ][:].astype(np.int64),
            "pred_tracking": f[
                geometry_dataset_keys["pred_tracking"]
            ][:].astype(np.float32),
            "frame_indices": f["frame_indices"][:].astype(np.int64),
            "attrs": dict(f.attrs),
            "geometry_key": geometry_key,
            "geometry_dataset_keys": geometry_dataset_keys,
        }

        if "pred_tracking_prior" in f:
            data["pred_tracking_prior"] = f["pred_tracking_prior"][:].astype(np.float32)
        elif "pred_tracking" in f:
            data["pred_tracking_prior"] = f["pred_tracking"][:].astype(np.float32)
        if "raw_images" in f:
            data["raw_images"] = f["raw_images"][:]
        if "global_encoder_images" in f:
            data["global_encoder_images"] = f["global_encoder_images"][:]
        if "tracking_correction" in f:
            data["tracking_correction_attrs"] = dict(f["tracking_correction"].attrs)

    return data


def make_texture_config_from_args(args: argparse.Namespace) -> AlphaTextureConfig:
    """
    Build AlphaTextureConfig from preset and command-line overrides.

    Presets:
      original
      otsu_area500
      percentile_area100
      percentile85_area100
    """
    if args.preset == "original":
        cfg = AlphaTextureConfig(
            texture_style="original",
            white_foreground=False,
        )

    elif args.preset == "otsu_area500":
        cfg = AlphaTextureConfig(
            texture_style="threshold_alpha",
            denoise="median",
            denoise_ksize=3,
            threshold_mode="otsu",
            open_ksize=3,
            close_ksize=5,
            morph_shape="ellipse",
            min_component_area=500,
            white_foreground=False,
        )

    elif args.preset in {"percentile90_area100", "percentile_area100"}:
        cfg = AlphaTextureConfig(
            texture_style="threshold_alpha",
            denoise="median",
            denoise_ksize=3,
            threshold_mode="percentile",
            percentile=90.0,
            open_ksize=3,
            close_ksize=5,
            morph_shape="ellipse",
            min_component_area=100,
            white_foreground=False,
        )

    elif args.preset == "percentile85_area100":
        cfg = AlphaTextureConfig(
            texture_style="threshold_alpha",
            denoise="median",
            denoise_ksize=3,
            threshold_mode="percentile",
            percentile=85.0,
            open_ksize=3,
            close_ksize=5,
            morph_shape="ellipse",
            min_component_area=100,
            white_foreground=False,
        )

    else:
        raise ValueError(f"Unknown preset: {args.preset}")

    # ------------------------------------------------------------
    # Optional overrides
    # ------------------------------------------------------------
    if args.texture_style is not None:
        cfg.texture_style = args.texture_style

    if args.texture_denoise is not None:
        cfg.denoise = args.texture_denoise

    if args.texture_denoise_ksize is not None:
        cfg.denoise_ksize = args.texture_denoise_ksize

    if args.texture_threshold_mode is not None:
        cfg.threshold_mode = args.texture_threshold_mode

    if args.texture_threshold is not None:
        cfg.fixed_threshold = args.texture_threshold

    if args.texture_percentile is not None:
        cfg.percentile = args.texture_percentile

    if args.texture_adaptive_block_size is not None:
        cfg.adaptive_block_size = args.texture_adaptive_block_size

    if args.texture_adaptive_c is not None:
        cfg.adaptive_c = args.texture_adaptive_c

    if args.texture_open_ksize is not None:
        cfg.open_ksize = args.texture_open_ksize

    if args.texture_close_ksize is not None:
        cfg.close_ksize = args.texture_close_ksize

    if args.texture_morph_shape is not None:
        cfg.morph_shape = args.texture_morph_shape

    if args.texture_min_component_area is not None:
        cfg.min_component_area = args.texture_min_component_area

    if args.texture_white_foreground:
        cfg.white_foreground = True

    return cfg


def export_textured_slices_obj(
    output_obj: Path,
    *,
    frame_corners_world: np.ndarray,
    texture_images: np.ndarray,
    texture_config: AlphaTextureConfig,
    texture_dir_name: str = "textures",
    material_prefix: str = "frame",
):
    """
    Export one textured quad per frame as OBJ + MTL + PNG textures.

    frame_corners_world:
      [N,4,3]
      corner order:
        0 top-left
        1 top-right
        2 bottom-right
        3 bottom-left

    texture_images:
      usually local_encoder_images, [N,1,H,W]
    """
    output_obj = Path(output_obj)
    output_obj.parent.mkdir(parents=True, exist_ok=True)

    if output_obj.suffix.lower() != ".obj":
        raise ValueError(f"output_obj must end with .obj, got: {output_obj}")

    n = frame_corners_world.shape[0]

    if len(texture_images) != n:
        raise ValueError(
            f"Number of textures must match number of frames: "
            f"len(texture_images)={len(texture_images)}, n={n}"
        )

    mtl_path = output_obj.with_suffix(".mtl")
    texture_dir = output_obj.parent / texture_dir_name
    texture_dir.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------
    # 1. Save PNG textures
    # ------------------------------------------------------------
    texture_rel_paths = []

    for i in range(n):
        tex_name = f"frame_{i:05d}.png"
        tex_path = texture_dir / tex_name

        tex_img = make_texture_image(
            texture_images[i],
            config=texture_config,
        )

        imageio.imwrite(tex_path, tex_img)
        texture_rel_paths.append(f"{texture_dir_name}/{tex_name}")

    # ------------------------------------------------------------
    # 2. Write MTL
    # ------------------------------------------------------------
    uses_alpha = texture_config.texture_style == "threshold_alpha"

    with mtl_path.open("w") as f:
        f.write("# Textured slice materials generated by export_pseudo3d_visualization.py\n")
        f.write(f"# texture_style={texture_config.texture_style}\n")
        f.write(f"# threshold_mode={texture_config.threshold_mode}\n")
        f.write(f"# denoise={texture_config.denoise}\n")
        f.write(f"# denoise_ksize={texture_config.denoise_ksize}\n")
        f.write(f"# fixed_threshold={texture_config.fixed_threshold}\n")
        f.write(f"# percentile={texture_config.percentile}\n")
        f.write(f"# open_ksize={texture_config.open_ksize}\n")
        f.write(f"# close_ksize={texture_config.close_ksize}\n")
        f.write(f"# morph_shape={texture_config.morph_shape}\n")
        f.write(f"# min_component_area={texture_config.min_component_area}\n")
        f.write(f"# white_foreground={texture_config.white_foreground}\n\n")

        for i, rel_tex in enumerate(texture_rel_paths):
            mat_name = f"{material_prefix}_{i:05d}"
            f.write(f"newmtl {mat_name}\n")
            f.write("Ka 1.000 1.000 1.000\n")
            f.write("Kd 1.000 1.000 1.000\n")
            f.write("Ks 0.000 0.000 0.000\n")
            f.write("d 1.0\n")
            f.write("illum 2\n")
            f.write(f"map_Kd {rel_tex}\n")

            if uses_alpha:
                f.write(f"map_d {rel_tex}\n")

            f.write("\n")

    # ------------------------------------------------------------
    # 3. Write OBJ
    # ------------------------------------------------------------
    with output_obj.open("w") as f:
        f.write("# Textured slice OBJ generated by export_pseudo3d_visualization.py\n")
        f.write(f"mtllib {mtl_path.name}\n\n")

        # Vertices
        for i in range(n):
            for p in frame_corners_world[i]:
                f.write(f"v {p[0]:.8f} {p[1]:.8f} {p[2]:.8f}\n")

        f.write("\n")

        # UV coordinates
        for _ in range(n):
            f.write("vt 0.0 1.0\n")
            f.write("vt 1.0 1.0\n")
            f.write("vt 1.0 0.0\n")
            f.write("vt 0.0 0.0\n")

        f.write("\n")

        # Faces
        for i in range(n):
            mat_name = f"{material_prefix}_{i:05d}"
            f.write(f"usemtl {mat_name}\n")

            v0 = i * 4 + 1
            v1 = i * 4 + 2
            v2 = i * 4 + 3
            v3 = i * 4 + 4

            vt0 = i * 4 + 1
            vt1 = i * 4 + 2
            vt2 = i * 4 + 3
            vt3 = i * 4 + 4

            f.write(f"f {v0}/{vt0} {v1}/{vt1} {v2}/{vt2} {v3}/{vt3}\n\n")

    print(f"Saved textured OBJ: {output_obj}")
    print(f"Saved textured MTL: {mtl_path}")
    print(f"Saved textures dir : {texture_dir}")


def make_pyvista_quad_mesh(vertices: np.ndarray, faces: np.ndarray) -> pv.PolyData:
    """
    Convert vertices [V,3] and quad faces [F,4] to PyVista PolyData.
    """
    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError(f"vertices must be [V,3], got {vertices.shape}")

    if faces.ndim != 2 or faces.shape[1] != 4:
        raise ValueError(f"faces must be [F,4], got {faces.shape}")

    faces_pv = np.hstack(
        [
            np.full((faces.shape[0], 1), 4, dtype=np.int64),
            faces.astype(np.int64),
        ]
    ).ravel()

    return pv.PolyData(vertices.astype(np.float32), faces_pv)


def make_slice_only_mesh(frame_corners_world: np.ndarray) -> pv.PolyData:
    """
    Rebuild mesh with one quad per slice and no side faces.
    """
    if frame_corners_world.ndim != 3 or frame_corners_world.shape[1:] != (4, 3):
        raise ValueError(
            f"frame_corners_world must be [N,4,3], got {frame_corners_world.shape}"
        )

    n = frame_corners_world.shape[0]
    vertices = frame_corners_world.reshape(n * 4, 3).astype(np.float32)

    faces = []
    for i in range(n):
        base = i * 4
        faces.append([base + 0, base + 1, base + 2, base + 3])

    return make_pyvista_quad_mesh(vertices, np.asarray(faces, dtype=np.int64))


def export_ply(
    output_ply: Path,
    *,
    vertices: np.ndarray,
    faces: np.ndarray,
    frame_corners_world: np.ndarray,
    show_only_slices: bool,
):
    """
    Export PLY for MeshLab/ParaView shape inspection.
    """
    output_ply = Path(output_ply)
    output_ply.parent.mkdir(parents=True, exist_ok=True)

    if show_only_slices:
        mesh = make_slice_only_mesh(frame_corners_world)
    else:
        mesh = make_pyvista_quad_mesh(vertices, faces)

    mesh.save(str(output_ply))
    print(f"Saved PLY: {output_ply}")


def add_trajectory(plotter: pv.Plotter, pred_tracking: np.ndarray):
    trajectory = pred_tracking[:, :3, 3].astype(np.float32)

    if len(trajectory) >= 2:
        line = pv.lines_from_points(trajectory)
        plotter.add_mesh(line, line_width=4, label="trajectory")

    start = pv.PolyData(trajectory[[0]])
    end = pv.PolyData(trajectory[[-1]])

    plotter.add_mesh(start, point_size=14, render_points_as_spheres=True, label="start")
    plotter.add_mesh(end, point_size=14, render_points_as_spheres=True, label="end")


def add_frame_labels(
    plotter: pv.Plotter,
    frame_corners_world: np.ndarray,
    frame_indices: np.ndarray,
    label_every: int,
):
    if label_every <= 0:
        return

    centers = frame_corners_world.mean(axis=1)
    label_points = []
    labels = []

    for i in range(0, len(centers), label_every):
        label_points.append(centers[i])
        labels.append(str(int(frame_indices[i])))

    if not label_points:
        return

    plotter.add_point_labels(
        np.asarray(label_points, dtype=np.float32),
        labels,
        font_size=12,
        point_size=6,
        shape_opacity=0.3,
        always_visible=True,
    )


def export_screenshot(
    output_png: Path,
    *,
    vertices: np.ndarray,
    faces: np.ndarray,
    frame_corners_world: np.ndarray,
    pred_tracking: np.ndarray,
    frame_indices: np.ndarray,
    show_only_slices: bool,
    show_edges: bool,
    show_trajectory: bool,
    label_every: int,
    window_width: int,
    window_height: int,
):
    """
    Export PyVista screenshot of the slice mesh.
    This screenshot is geometry-only. Textured preview is intended for Blender.
    """
    output_png = Path(output_png)
    output_png.parent.mkdir(parents=True, exist_ok=True)

    if show_only_slices:
        mesh = make_slice_only_mesh(frame_corners_world)
    else:
        mesh = make_pyvista_quad_mesh(vertices, faces)

    plotter = pv.Plotter(off_screen=True, window_size=(window_width, window_height))
    plotter.set_background("white")

    plotter.add_mesh(
        mesh,
        opacity=0.35,
        show_edges=show_edges,
        edge_color="black",
        label="slice mesh",
    )

    if show_trajectory:
        add_trajectory(plotter, pred_tracking)

    if label_every > 0:
        add_frame_labels(
            plotter,
            frame_corners_world=frame_corners_world,
            frame_indices=frame_indices,
            label_every=label_every,
        )

    plotter.add_axes()
    plotter.add_legend()
    plotter.camera_position = "iso"
    plotter.reset_camera()

    plotter.show(screenshot=str(output_png), auto_close=True)
    print(f"Saved screenshot: {output_png}")


def estimate_tracking_progress_axis(
    pred_tracking: np.ndarray,
    tracking_correction_attrs: dict[str, Any] | None = None,
    *,
    method: str = "attrs",
    window: Optional[int] = None,
    eps: float = 1e-8,
) -> tuple[np.ndarray, dict[str, Any]]:
    """
    Estimate representative progress axis for Blender debug export.
    """
    attrs = tracking_correction_attrs or {}
    if method == "attrs":
        method = str(attrs.get("initial_direction_method", "global_mean"))

    if window is None:
        window = int(attrs.get("initial_direction_window", 15))

    centers = pred_tracking[:, :3, 3].astype(np.float64)

    if method == "start_to_end":
        axis_raw = centers[-1] - centers[0]
        axis_norm = float(np.linalg.norm(axis_raw))
        if axis_norm <= eps or not np.isfinite(axis_norm):
            raise ValueError(f"Cannot estimate start_to_end axis: norm={axis_norm}")
        return axis_raw / axis_norm, {
            "axis_method": method,
            "axis_num_candidates": int(len(centers)),
            "axis_raw_norm": axis_norm,
        }

    steps = np.diff(centers, axis=0)
    finite_steps = np.isfinite(steps).all(axis=1)
    step_lengths = np.linalg.norm(np.where(finite_steps[:, None], steps, 0.0), axis=1)
    valid_mask = finite_steps & (step_lengths > eps)
    valid_indices = np.flatnonzero(valid_mask)

    if valid_indices.size == 0:
        raise ValueError("Cannot estimate progress axis without valid steps.")

    if method == "first_valid":
        candidate_indices = valid_indices[:1]
    elif method == "early_mean":
        if window <= 0:
            raise ValueError(f"early_mean window must be > 0, got {window}")
        candidate_indices = valid_indices[:window]
    elif method == "global_mean":
        candidate_indices = valid_indices
    else:
        raise ValueError(
            f"Unknown tracking_debug_axis_method='{method}'. "
            "Choose from: attrs, first_valid, early_mean, global_mean, start_to_end"
        )

    candidate_dirs = steps[candidate_indices] / step_lengths[candidate_indices, None]
    axis_raw = candidate_dirs.mean(axis=0)
    axis_norm = float(np.linalg.norm(axis_raw))
    if axis_norm <= eps or not np.isfinite(axis_norm):
        raise ValueError(f"Cannot estimate progress axis: norm={axis_norm}")

    return axis_raw / axis_norm, {
        "axis_method": method,
        "axis_num_candidates": int(candidate_indices.size),
        "axis_raw_norm": axis_norm,
    }


def export_tracking_debug_obj(
    output_obj: Path,
    *,
    pred_tracking: np.ndarray,
    pred_tracking_for_axis: np.ndarray,
    tracking_correction_attrs: dict[str, Any] | None = None,
    axis_method: str = "attrs",
    axis_window: Optional[int] = None,
    axis_length: float = 0.0,
    point_size: float = 0.25,
):
    """
    Export center trajectory, center point crosses, and representative axis as OBJ.
    """
    output_obj = Path(output_obj)
    output_obj.parent.mkdir(parents=True, exist_ok=True)
    if output_obj.suffix.lower() != ".obj":
        raise ValueError(f"output_obj must end with .obj, got: {output_obj}")

    centers = pred_tracking[:, :3, 3].astype(np.float64)
    axis, axis_meta = estimate_tracking_progress_axis(
        pred_tracking_for_axis,
        tracking_correction_attrs=tracking_correction_attrs,
        method=axis_method,
        window=axis_window,
    )

    extent = float(np.linalg.norm(centers[-1] - centers[0])) if len(centers) > 1 else 1.0
    if axis_length <= 0.0:
        axis_length = max(extent * 1.1, 1.0)

    axis_start = centers[0]
    axis_end = centers[0] + axis * float(axis_length)

    mtl_path = output_obj.with_suffix(".mtl")
    with mtl_path.open("w") as f:
        f.write("# Tracking debug materials\n")
        f.write("newmtl trajectory_red\nKd 1.0 0.05 0.05\nKa 1.0 0.05 0.05\n\n")
        f.write("newmtl progress_axis_blue\nKd 0.05 0.2 1.0\nKa 0.05 0.2 1.0\n\n")
        f.write("newmtl center_points_green\nKd 0.05 0.8 0.1\nKa 0.05 0.8 0.1\n\n")

    with output_obj.open("w") as f:
        f.write("# Tracking debug OBJ generated by export_pseudo3d_visualization.py\n")
        f.write(f"# axis_method={axis_meta['axis_method']}\n")
        f.write(f"# axis_num_candidates={axis_meta['axis_num_candidates']}\n")
        f.write(f"# axis_raw_norm={axis_meta['axis_raw_norm']}\n")
        f.write(f"# axis=({axis[0]:.8f}, {axis[1]:.8f}, {axis[2]:.8f})\n")
        f.write(f"mtllib {mtl_path.name}\n\n")

        trajectory_vertex_start = 1
        for p in centers:
            f.write(f"v {p[0]:.8f} {p[1]:.8f} {p[2]:.8f}\n")

        axis_vertex_start = trajectory_vertex_start + len(centers)
        f.write(f"v {axis_start[0]:.8f} {axis_start[1]:.8f} {axis_start[2]:.8f}\n")
        f.write(f"v {axis_end[0]:.8f} {axis_end[1]:.8f} {axis_end[2]:.8f}\n")

        cross_vertex_start = axis_vertex_start + 2
        half = float(point_size) * 0.5
        offsets = np.asarray(
            [
                [-half, 0.0, 0.0],
                [half, 0.0, 0.0],
                [0.0, -half, 0.0],
                [0.0, half, 0.0],
                [0.0, 0.0, -half],
                [0.0, 0.0, half],
            ],
            dtype=np.float64,
        )
        for p in centers:
            for offset in offsets:
                q = p + offset
                f.write(f"v {q[0]:.8f} {q[1]:.8f} {q[2]:.8f}\n")

        f.write("\nusemtl trajectory_red\n")
        trajectory_indices = " ".join(
            str(trajectory_vertex_start + i) for i in range(len(centers))
        )
        f.write(f"l {trajectory_indices}\n")

        f.write("\nusemtl progress_axis_blue\n")
        f.write(f"l {axis_vertex_start} {axis_vertex_start + 1}\n")

        f.write("\nusemtl center_points_green\n")
        for i in range(len(centers)):
            base = cross_vertex_start + i * 6
            f.write(f"l {base} {base + 1}\n")
            f.write(f"l {base + 2} {base + 3}\n")
            f.write(f"l {base + 4} {base + 5}\n")

    print(f"Saved tracking debug OBJ: {output_obj}")
    print(f"Saved tracking debug MTL: {mtl_path}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Export visualization files from a pseudo-3D h5. "
            "This script does not run DualTrack inference."
        )
    )

    parser.add_argument(
        "--input_h5",
        type=Path,
        required=True,
        help="Input pseudo-3D h5 file.",
    )

    # ------------------------------------------------------------
    # Main export outputs
    # ------------------------------------------------------------
    parser.add_argument(
        "--export_textured_obj",
        type=Path,
        default=None,
        help="Output textured OBJ path for Blender.",
    )

    parser.add_argument(
        "--export_ply",
        type=Path,
        default=None,
        help="Optional output PLY path for geometry inspection.",
    )

    parser.add_argument(
        "--screenshot",
        type=Path,
        default=None,
        help="Optional geometry-only screenshot PNG path.",
    )

    parser.add_argument(
        "--export_tracking_debug_obj",
        type=Path,
        default=None,
        help="Optional OBJ path for center trajectory and representative axis.",
    )

    parser.add_argument(
        "--texture_dir_name",
        type=str,
        default="textures",
        help="Texture directory name relative to OBJ file.",
    )

    parser.add_argument(
        "--geometry_key",
        type=str,
        default="prior",
        choices=["prior", "corr"],
        help=(
            "Geometry to export from h5. "
            "prior uses frame_corners_world/frame_mesh_vertices/frame_mesh_faces. "
            "corr uses the corresponding *_corr datasets."
        ),
    )

    # ------------------------------------------------------------
    # Preset
    # ------------------------------------------------------------
    parser.add_argument(
        "--preset",
        type=str,
        default="original",
        choices=[
            "original",
            "otsu_area500",
            "percentile90_area100",
            "percentile_area100",
            "percentile85_area100",
        ],
        help=(
            "Texture processing preset. "
            "original: no alpha. "
            "otsu_area500: Otsu + component area 500. "
            "percentile90_area100: percentile90 + component area 100. "
            "percentile85_area100: percentile85 + component area 100."
        ),
    )

    # ------------------------------------------------------------
    # Optional texture overrides
    # ------------------------------------------------------------
    parser.add_argument(
        "--texture_style",
        type=str,
        default=None,
        choices=["original", "threshold_alpha"],
        help="Override texture style.",
    )

    parser.add_argument(
        "--texture_denoise",
        type=str,
        default=None,
        choices=["none", "median", "gaussian", "bilateral"],
        help="Override denoise mode.",
    )

    parser.add_argument(
        "--texture_denoise_ksize",
        type=int,
        default=None,
        help="Override denoise kernel size.",
    )

    parser.add_argument(
        "--texture_threshold_mode",
        type=str,
        default=None,
        choices=["fixed", "otsu", "percentile", "adaptive"],
        help="Override threshold mode.",
    )

    parser.add_argument(
        "--texture_threshold",
        type=int,
        default=None,
        help="Override fixed threshold.",
    )

    parser.add_argument(
        "--texture_percentile",
        type=float,
        default=None,
        help="Override percentile value.",
    )

    parser.add_argument(
        "--texture_adaptive_block_size",
        type=int,
        default=None,
        help="Override adaptive threshold block size.",
    )

    parser.add_argument(
        "--texture_adaptive_c",
        type=float,
        default=None,
        help="Override adaptive threshold C.",
    )

    parser.add_argument(
        "--texture_open_ksize",
        type=int,
        default=None,
        help="Override morphology opening kernel size.",
    )

    parser.add_argument(
        "--texture_close_ksize",
        type=int,
        default=None,
        help="Override morphology closing kernel size.",
    )

    parser.add_argument(
        "--texture_morph_shape",
        type=str,
        default=None,
        choices=["rect", "ellipse", "cross"],
        help="Override morphology kernel shape.",
    )

    parser.add_argument(
        "--texture_min_component_area",
        type=int,
        default=None,
        help="Override minimum connected component area.",
    )

    parser.add_argument(
        "--texture_white_foreground",
        action="store_true",
        help="Force visible alpha foreground pixels to pure white.",
    )

    # ------------------------------------------------------------
    # Geometry preview options
    # ------------------------------------------------------------
    parser.add_argument(
        "--show_only_slices",
        action="store_true",
        help="For PLY/screenshot, rebuild mesh with one quad per slice and no side faces.",
    )

    parser.add_argument(
        "--show_edges",
        action="store_true",
        help="Show mesh edges in screenshot.",
    )

    parser.add_argument(
        "--show_trajectory",
        action="store_true",
        help="Show trajectory in screenshot.",
    )

    parser.add_argument(
        "--label_every",
        type=int,
        default=0,
        help="Show original frame index label every N frames in screenshot. 0 disables labels.",
    )

    parser.add_argument(
        "--window_width",
        type=int,
        default=1400,
        help="Screenshot window width.",
    )

    parser.add_argument(
        "--window_height",
        type=int,
        default=1000,
        help="Screenshot window height.",
    )

    parser.add_argument(
        "--tracking_debug_axis_method",
        type=str,
        default="attrs",
        choices=["attrs", "first_valid", "early_mean", "global_mean", "start_to_end"],
        help="Representative axis method for tracking debug OBJ.",
    )

    parser.add_argument(
        "--tracking_debug_axis_window",
        type=int,
        default=None,
        help="Override early_mean valid-step window for tracking debug OBJ.",
    )

    parser.add_argument(
        "--tracking_debug_axis_length",
        type=float,
        default=0.0,
        help="Axis line length for tracking debug OBJ. 0 uses trajectory extent.",
    )

    parser.add_argument(
        "--tracking_debug_point_size",
        type=float,
        default=0.25,
        help="Center cross size for tracking debug OBJ.",
    )

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()

    data = load_pseudo3d_h5(args.input_h5, geometry_key=args.geometry_key)

    local_images = data["local_encoder_images"]
    frame_corners_world = data["frame_corners_world"]
    vertices = data["frame_mesh_vertices"]
    faces = data["frame_mesh_faces"]
    pred_tracking = data["pred_tracking"]
    pred_tracking_prior = data.get("pred_tracking_prior", pred_tracking)
    frame_indices = data["frame_indices"]

    print("Loaded pseudo-3D h5:")
    print(f"  input_h5           : {args.input_h5}")
    print(f"  geometry_key       : {data['geometry_key']}")
    print(f"  local_images       : {local_images.shape}")
    print(f"  frame_corners_world: {frame_corners_world.shape}")
    print(f"  vertices           : {vertices.shape}")
    print(f"  faces              : {faces.shape}")
    print(f"  pred_tracking      : {pred_tracking.shape}")
    print(f"  frame_indices      : {frame_indices.shape}")

    print("\nGeometry datasets:")
    for key, dataset_key in data["geometry_dataset_keys"].items():
        print(f"  {key}: {dataset_key}")

    if "tracking_correction_attrs" in data:
        print("\nTracking correction metadata:")
        for key, value in data["tracking_correction_attrs"].items():
            print(f"  {key}: {value}")

    texture_config = make_texture_config_from_args(args)

    print("\nTexture config:")
    for k, v in texture_config.__dict__.items():
        print(f"  {k}: {v}")

    if args.export_textured_obj is not None:
        export_textured_slices_obj(
            args.export_textured_obj,
            frame_corners_world=frame_corners_world,
            texture_images=local_images,
            texture_config=texture_config,
            texture_dir_name=args.texture_dir_name,
        )

    if args.export_ply is not None:
        export_ply(
            args.export_ply,
            vertices=vertices,
            faces=faces,
            frame_corners_world=frame_corners_world,
            show_only_slices=args.show_only_slices,
        )

    if args.screenshot is not None:
        export_screenshot(
            args.screenshot,
            vertices=vertices,
            faces=faces,
            frame_corners_world=frame_corners_world,
            pred_tracking=pred_tracking,
            frame_indices=frame_indices,
            show_only_slices=args.show_only_slices,
            show_edges=args.show_edges,
            show_trajectory=args.show_trajectory,
            label_every=args.label_every,
            window_width=args.window_width,
            window_height=args.window_height,
        )

    if args.export_tracking_debug_obj is not None:
        export_tracking_debug_obj(
            args.export_tracking_debug_obj,
            pred_tracking=pred_tracking,
            pred_tracking_for_axis=pred_tracking_prior,
            tracking_correction_attrs=data.get("tracking_correction_attrs", {}),
            axis_method=args.tracking_debug_axis_method,
            axis_window=args.tracking_debug_axis_window,
            axis_length=args.tracking_debug_axis_length,
            point_size=args.tracking_debug_point_size,
        )

    print("\nDone.")


if __name__ == "__main__":
    main()
