from __future__ import annotations

import argparse
import csv
import shutil
from pathlib import Path


def _format_pattern(pattern: str, *, mode: str) -> str:
    return pattern.format(mode=mode)


def _video_dir_name(path: Path, *, source_root: Path) -> str:
    rel = path.relative_to(source_root)
    if len(rel.parts) <= 1:
        return path.stem
    return rel.parts[0]


def collect_files(
    *,
    source_root: Path,
    mode: str,
    pattern: str,
) -> list[Path]:
    source_root = Path(source_root)
    if not source_root.exists():
        raise FileNotFoundError(f"source_root not found: {source_root}")
    if not source_root.is_dir():
        raise NotADirectoryError(f"source_root is not a directory: {source_root}")

    glob_pattern = _format_pattern(pattern, mode=mode)
    return sorted(path for path in source_root.rglob(glob_pattern) if path.is_file())


def copy_files(
    *,
    files: list[Path],
    source_root: Path,
    output_dir: Path,
    overwrite: bool,
    dry_run: bool,
) -> list[dict[str, str]]:
    output_dir = Path(output_dir)
    rows = []
    seen_destinations: set[Path] = set()

    if not dry_run:
        output_dir.mkdir(parents=True, exist_ok=True)

    for src in files:
        dst = output_dir / src.name
        video_dir = _video_dir_name(src, source_root=source_root)

        status = "copied"
        if dst in seen_destinations:
            raise FileExistsError(f"Duplicate destination in this run: {dst}")
        seen_destinations.add(dst)

        if dst.exists() and not overwrite:
            status = "skipped_exists"
        elif dry_run:
            status = "dry_run"
        else:
            shutil.copy2(src, dst)

        rows.append(
            {
                "status": status,
                "video_dir": video_dir,
                "source_path": str(src),
                "destination_path": str(dst),
            }
        )

    return rows


def write_manifest(path: Path, rows: list[dict[str, str]]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["status", "video_dir", "source_path", "destination_path"]
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Collect annotated pseudo-3D point cloud h5 files generated by "
            "batch_annotate_pseudo3d_point_cloud.py into one directory."
        )
    )
    parser.add_argument(
        "--source_root",
        type=Path,
        required=True,
        help=(
            "Root containing per-video directories, for example "
            "pseudo3d_visualizations/<RUN_NAME>."
        ),
    )
    parser.add_argument(
        "--output_dir",
        type=Path,
        required=True,
        help="Directory where matching annotated h5 files are copied flat.",
    )
    parser.add_argument(
        "--mode",
        type=str,
        required=True,
        choices=["foreground", "grid", "dense"],
        help="Point mode suffix to collect.",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_annotated_{mode}.h5",
        help=(
            "Recursive glob pattern relative to source_root. "
            "The token {mode} is replaced by --mode. "
            "Default matches both <video>_annotated_<mode>.h5 and "
            "<video>_pointcloud_annotated_<mode>.h5."
        ),
    )
    parser.add_argument(
        "--manifest_csv",
        type=Path,
        default=None,
        help="Optional CSV manifest listing copied/skipped files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files in output_dir.",
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Print intended copies without writing files.",
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    files = collect_files(
        source_root=args.source_root,
        mode=args.mode,
        pattern=args.pattern,
    )
    rows = copy_files(
        files=files,
        source_root=args.source_root,
        output_dir=args.output_dir,
        overwrite=args.overwrite,
        dry_run=args.dry_run,
    )

    if args.manifest_csv is not None:
        write_manifest(args.manifest_csv, rows)

    print("Collect annotated pseudo-3D h5:")
    print(f"  source_root : {args.source_root}")
    print(f"  output_dir  : {args.output_dir}")
    print(f"  mode        : {args.mode}")
    print(f"  pattern     : {_format_pattern(args.pattern, mode=args.mode)}")
    print(f"  found       : {len(files)}")
    print(f"  copied      : {sum(row['status'] == 'copied' for row in rows)}")
    print(f"  skipped     : {sum(row['status'] == 'skipped_exists' for row in rows)}")
    print(f"  dry_run     : {args.dry_run}")


if __name__ == "__main__":
    main()
