#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# Run from DualTrack repository root
# ------------------------------------------------------------
cd /mnt/data/3d_projects/models/Stage2to4

# ------------------------------------------------------------
# input path info
# ------------------------------------------------------------
OUTPUT_ROOT="/mnt/data/3d_projects/pseudo3d_dataset"
RUN_NAME="260712"
H5_DIR="${OUTPUT_ROOT}/pseudo3d_outputs/${RUN_NAME}"

# h5 files generated by batch_infer_video_to_pseudo3d_h5.py are expected as:
#   ${H5_DIR}/${VIDEO}${OUTPUT_SUFFIX}.h5
OUTPUT_SUFFIX="_ts448_oym96_corr"
H5_PATTERN="*${OUTPUT_SUFFIX}.h5"

# ------------------------------------------------------------
# output path info
# ------------------------------------------------------------
VIS_DIR="${OUTPUT_ROOT}/pseudo3d_visualizations/${RUN_NAME}"
DETAIL="percentile85_area100"
GEOMETRY_KEY="corr"

mkdir -p "${VIS_DIR}"

python pseudo3d/batch/export/batch_export_pseudo3d_visualization.py \
  --input_dir "${H5_DIR}" \
  --pattern "${H5_PATTERN}" \
  --output_root "${VIS_DIR}" \
  --preset "${DETAIL}" \
  --geometry_key "${GEOMETRY_KEY}" \
  --texture_percentile 85 \
  --texture_min_component_area 100 \
  --export_tracking_debug_obj \
  --skip_existing \
  --continue_on_error
